module.exports = {
    // index: function(req, res) {
    //     return res.render('Dashboard', _.extend({}, toView, {
    //         pageTitle: 'Система мониторинга электронных сервисов ФНС России',
    //         title: 'Система мониторинга электронных сервисов ФНС России',
    //         bc: [
    //             { name: 'Список сервисов', href: '/' },
    //             { name: 'test', href: '/test' },
    //         ],
    //         vue: 'Vues/dashboard/dashboard.js'
    //     }));
    // },
    index: function(req, res) {
        return res.render('Dashboard', _.extend({}, toView, {
            pageTitle: 'Система мониторинга электронных сервисов ФНС России',
            title: 'Система мониторинга электронных сервисов ФНС России',
            bc: [
                { name: 'Главная', href: '/' },
                // { name: 'Все группы', href: '/test' },
            ],
            vue: 'Vues/dashboard/dashboard.js',
        }));
    },
    serviceGroups: function(req, res) {
        return res.render('Dashboard', _.extend({}, toView, {
            pageTitle: 'Система мониторинга электронных сервисов ФНС России',
            title: 'Система мониторинга электронных сервисов ФНС России',
            bc: [
                { name: 'Главная', href: '/' },
                { name: 'Группы сервисов', href: '/serviceGroups' },
            ],
            vue: 'Vues/serviceGroups/serviceGroups.js',
        }));
    },
    getTestData: function(req, res) {
        var period = req.param('period');
        console.log(period);
        var datas = [
                {
                    pies: [
                       {    description: 'Налог',
                            status: "2",
                            green: "10",
                            yellow: "20",
                            red: "60",
                            total: "90",
                            startTime: moment().add(-40, 's'),
                       },
                       {    description: 'ЛК',
                            status: "3",
                            green: "20",
                            yellow: "20",
                            red: "100",
                            total: "130",
                            startTime: moment().add(-5, 's'),
                       },
                       {    description: 'АС',
                            status: "5",
                            green: "14",
                            yellow: "20",
                            red: "",
                            total: "70",
                            startTime: moment().add(-3, 's'),
                       },
                    ],
                },
                {
                    pies: [
                       {    description: 'Налог',
                            status: "2",
                            green: "10",
                            yellow: "20",
                            red: "60",
                            total: "90",
                            startTime: moment().add(-40, 's'),
                       },
                       {    description: 'ЛК',
                            status: "3",
                            green: "20",
                            yellow: "20",
                            red: "100",
                            total: "130",
                            startTime: moment().add(-5, 's'),
                       },
                       {    description: 'АС',
                            status: "5",
                            green: "14",
                            yellow: "20",
                            red: "",
                            total: "70",
                            startTime: moment().add(-3, 's'),
                       },
                    ],
                },
                {
                    pies: [
                       {    description: 'Налог',
                            status: "2",
                            green: "10",
                            yellow: "20",
                            red: "60",
                            total: "90",
                            startTime: moment().add(-40, 's'),
                       },
                       {    description: 'ЛК',
                            status: "3",
                            green: "20",
                            yellow: "20",
                            red: "100",
                            total: "130",
                            startTime: moment().add(-5, 's'),
                       },
                       {    description: 'АС',
                            status: "5",
                            green: "14",
                            yellow: "20",
                            red: "",
                            total: "70",
                            startTime: moment().add(-3, 's'),
                       },
                    ],
                },
                {
                    pies: [
                       {    description: 'Налог',
                            status: "2",
                            green: "10",
                            yellow: "20",
                            red: "60",
                            total: "90",
                            startTime: moment().add(-40, 's'),
                       },
                       {    description: 'ЛК',
                            status: "3",
                            green: "20",
                            yellow: "20",
                            red: "100",
                            total: "130",
                            startTime: moment().add(-5, 's'),
                       },
                       {    description: 'АС',
                            status: "5",
                            green: "14",
                            yellow: "20",
                            red: "",
                            total: "70",
                            startTime: moment().add(-3, 's'),
                       },
                    ],
                },
                {
                    pies: [
                       {    description: 'Налог',
                            status: "2",
                            green: "10",
                            yellow: "20",
                            red: "60",
                            total: "90",
                            startTime: moment().add(-40, 's'),
                       },
                       {    description: 'ЛК',
                            status: "3",
                            green: "20",
                            yellow: "20",
                            red: "100",
                            total: "130",
                            startTime: moment().add(-5, 's'),
                       },
                       {    description: 'АС',
                            status: "5",
                            green: "14",
                            yellow: "20",
                            red: "",
                            total: "70",
                            startTime: moment().add(-3, 's'),
                       },
                    ],
                },
            ]

        return res.send(datas[period].pies);
    },
};
